# Fit the Model/Algorithm and use it to make predictions on our data

Now you've chosen a model, the next step is to have it learn from the data so it can be used for predictions in the future.

If you've followed through, you've seen a few examples of this already.

### 3.1 Fitting a model to data

In Scikit-Learn, the process of having a machine learning model learn patterns from a dataset involves calling the `fit()` method and passing it data, such as, `fit(X, y)`.

Where `X` is a feature array and `y` is a target array.

Other names for `X` include:
* Data
* Feature variables
* Features

Other names for `y` include:
* Labels
* Target variable

For supervised learning there is usually an `X` and `y`. For unsupervised learning, there's no `y` (no labels).


In [1]:
#Standard libraries
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
heart_disease = pd.read_csv('Dataset/heart-disease.csv')
heart_disease.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
#Import the Randomforest estimator
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

#Set a random seed
np.random.seed(42)

#Getting the data ready
X = heart_disease.drop('target', axis = 1)
y = heart_disease['target']

#Splitting the dataset

X_train,X_test,y_train,y_test = train_test_split(X,y , test_size= 0.2)

#Instantiate algo
clf = RandomForestClassifier()

#Fitting the model(Training the model)
clf.fit(X_train,y_train)

#Evaluate the score/Accuracy
clf.score(X_test,y_test)

0.8524590163934426

Calling the `fit()` method will cause the machine learning algorithm to attempt to find patterns between `X` and `y`. Or if there's no `y`, it'll only find the patterns within `X`.

* Fitting the model on the data involves passing it the data and asking it to figure out the patterns.

* If there are labels (supervised learning), the model tries to work out the relationship between the data and the labels.

* If there are no labels (unsupervised learning), the model tries to find patterns and group similar samples together.

### Make Predictions using the model
The whole point of training a machine learning model is to use it to make some kind of prediction in the future.

Once our model instance is trained, you can use the predict() method to predict a target value given a set of features. In other words, use the model, along with some unlabelled data to predict the label.

**Note:** data you predict on has to be in the same shape as data you trained on.

Their are 2 ways to predict on a model:
   1. predict()
   2. predict_proba()

In [5]:
# Use a Trained model to make Predictions
clf.predict(np.array([1,8,8,3,4])) # This will not Work as for prediction we need the same size data

ValueError: Expected 2D array, got 1D array instead:
array=[1. 8. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [7]:
 X_test.shape

(61, 13)

In [8]:
clf.predict(X_test) # This is the predicted data

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [9]:
np.array(y_test) # This is the actual data

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [11]:
# Compare Predictions to Truth Labels to evaluate the Model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

It's standard practice to save these predictions to a variable named something like `y_preds` for later comparison to `y_test` or `y_true` (usually same as `y_test` just another name).

In [12]:
clf.score(X_test, y_test) #Another way to see score

0.8524590163934426

Another way of doing this is with Scikit-Learn's [`accuracy_score()`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html) function.

In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)  

0.8524590163934426

**Making the prediction by using `predict_proba()`**
Use this if someone asks you "what's the probability your model is assigning to each prediction?"

In [18]:
clf.predict_proba(X_test[:5]) #[0,1] here the 0.89 indicates the probability to be 0 and 0.11 probability to be 1

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [19]:
#Lets do the ssame using the predict function
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [20]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

**Predict can also be used in Regression Problems**

In [21]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Import Boston Housing Dataset
from sklearn.datasets import load_boston

boston = load_boston()
boston

boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"] = pd.Series(boston['target'])
boston_df.head()

# Create the Data
x = boston_df.drop("target", axis=1)
y = boston_df["target"]

# Split into Train and test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

# Instantiate the Fit model
model = RandomForestRegressor().fit(x_train, y_train)

# Make Predictions
y_preds = model.predict(x_test)

In [22]:
y_preds[:5]

array([23.002, 30.826, 16.734, 23.467, 16.853])

In [24]:
np.array(y_test[:5])

array([23.6, 32.4, 13.6, 22.8, 16.1])

In [25]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.1226372549019623