In [3]:
import numpy as np
import pandas as pd

### Example  Nut Butter Store 

In [2]:
np.random.seed(0)
#Number of jar Sold
sales_amount = np.random.randint(20, size = (5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [5]:
# creat a weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tue", "Wed", "Thur", "Fri"],
                           columns= ["Almond Buter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Buter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thur             4              6             12
Fri              1              6              7

In [7]:
#Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [9]:
#Create butter_prices Dataframe
butter_price = pd.DataFrame(prices.reshape(1,3),
                           index = ["Price"],
                           columns =["Almond Buter", "Peanut Butter", "Cashew Butter"] )
butter_price

Almond Buter  Peanut Butter  Cashew Butter
Price            10              8             12

In [11]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

Shape arent aligned we had to transpose 

In [13]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [14]:
#Create Daily_sales
butter_price.shape, weekly_sales.shape

((1, 3), (5, 3))

In [15]:
daily_sales = butter_price.dot(weekly_sales.T)

In [16]:
daily_sales

Mon  Tue  Wed  Thur  Fri
Price  240  138  458   232  142

In [17]:
weekly_sales["Total($)"] = daily_sales.T #Without transpose we get the dimension error

In [18]:
weekly_sales

Almond Buter  Peanut Butter  Cashew Butter  Total($)
Mon             12             15              0       240
Tue              3              3              7       138
Wed              9             19             18       458
Thur             4              6             12       232
Fri              1              6              7       142