## <font color=purple>Turning Images into Numpy Arrays

### Importing Libray

In [1]:
import numpy as np

### Importing the image

In [5]:
#Turn an image into a Numpy array
from matplotlib.image import imread

panda = imread("C:/Users/Admin/Python/Numpy/panda.png")

In [7]:
print(type(panda))

<class 'numpy.ndarray'>


In [8]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

### Practicing all that we learnt

In [9]:
panda.size

24465000

In [10]:
panda.shape

(2330, 3500, 3)

In [11]:
panda.ndim

3

In [23]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [20]:
panda[:2,:3,:3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667]]], dtype=float32)

In [24]:
panda.dtype

dtype('float32')

In [32]:
panda.mean()

0.28040403

In [33]:
panda.min()

0.0

In [34]:
panda.max()

1.0

In [35]:
panda.all() #Returns True if all elements evaluate to True.

False

In [38]:
panda.any() #Returns True if any of the elements of `panda` evaluate to True.

True

In [39]:
panda.argsort()

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       ...,

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        ...,
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]], dtype=int64)

In [40]:
panda.sort()

In [42]:
panda.view()

array([[[0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        ...,
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589]],

       [[0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        ...,
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589]],

       [[0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        [0.05490196, 0.06666667, 0.10588235],
        ...,
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589],
        [0.09411765, 0.12941177, 0.16470589]],

       ...,

       [[0.05490196, 0.07450981, 0.13333334],
        [0.04313726, 0.0627451 , 0.12156863],
        [0.03137255, 0

In [43]:
np.sum(panda)

6860084.5

In [44]:
np.sqrt(panda)

array([[[0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        ...,
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974]],

       [[0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        ...,
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974]],

       [[0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        [0.23431167, 0.2581989 , 0.3253957 ],
        ...,
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974],
        [0.306786  , 0.35973847, 0.40583974]],

       ...,

       [[0.23431167, 0.27296484, 0.3651484 ],
        [0.2076951 , 0.2504897 , 0.34866694],
        [0.17712298, 0

In [45]:
np.max(panda)

1.0

In [46]:
np.std(panda)

0.28024203

In [47]:
np.var(panda)

0.078535594